# Generated by Django 2.0.5 on 2018-05-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='social_networks',
        ),
    ]
