# Generated by Django 2.0.5 on 2018-05-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventor', '0003_listing_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='object_id',
        ),
    ]
