# Generated by Django 2.2.4 on 2020-06-09 17:30

from django.db import migrations, models
import internationalflavor.countries.models
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=internationalflavor.countries.models.CountryField(blank=True, db_index=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Reg. No'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='street and number'),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='TAX ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=50, verbose_name='team/club'),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_id',
            field=internationalflavor.vat_number.models.VATNumberField(blank=True, verbose_name='VAT ID'),
        ),
    ]
