# Generated by Django 2.2.4 on 2020-06-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200609_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vat_id',
        ),
    ]
