# Generated by Django 2.2.4 on 2020-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200618_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('sk', 'Slovak'), ('en', 'English')], default='', max_length=5, verbose_name='language'),
            preserve_default=False,
        ),
    ]
