# Generated by Django 2.2.4 on 2020-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_marketing_purposes',
            field=models.BooleanField(default=True, verbose_name='Marketing purposes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_privacy_policy',
            field=models.BooleanField(default=True, verbose_name='Privacy policy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_social_networks_sharing',
            field=models.BooleanField(default=True, verbose_name='Sharing on social networks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_terms_and_conditions',
            field=models.BooleanField(default=True, verbose_name='Terms and conditions'),
            preserve_default=False,
        ),
    ]
