# Generated by Django 2.2.4 on 2020-07-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200707_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agreed_marketing_purposes',
            new_name='agree_marketing_purposes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='agreed_privacy_policy',
            new_name='agree_privacy_policy',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='agreed_social_networks_sharing',
            new_name='agree_social_networks_sharing',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='agreed_terms_and_conditions',
            new_name='agree_terms_and_conditions',
        ),
    ]
