# Generated by Django 2.2.4 on 2020-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200707_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree_marketing_purposes',
            field=models.BooleanField(default=True, verbose_name='Marketing purposes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agree_privacy_policy',
            field=models.BooleanField(default=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agree_social_networks_sharing',
            field=models.BooleanField(default=True, verbose_name='Sharing on social networks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agree_terms_and_conditions',
            field=models.BooleanField(default=True, verbose_name='Terms and conditions'),
        ),
    ]
