# Generated by Django 2.2.14 on 2021-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20210523_2204'),
        ('accounts', '0007_auto_20200707_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_listings',
            field=models.ManyToManyField(related_name='favorite_of_users', to='listings.Listing', verbose_name='favorite listings'),
        ),
    ]
