# Generated by Django 2.2.4 on 2020-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='robots',
            field=models.CharField(blank=True, choices=[('index', 'index'), ('noindex', 'noindex'), ('follow', 'follow'), ('noindex, follow', 'noindex, follow'), ('index, nofollow', 'index, nofollow'), ('noindex, nofollow', 'noindex, nofollow')], default='', max_length=17, verbose_name='robots'),
        ),
    ]
