# Generated by Django 2.2.4 on 2020-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seo_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='path',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='request path'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='robots',
            field=models.CharField(blank=True, choices=[('index', 'index'), ('noindex', 'noindex'), ('follow', 'follow'), ('noindex, follow', 'noindex, follow'), ('index, nofollow', 'index, nofollow'), ('noindex, nofollow', 'noindex, nofollow')], default='', help_text='Default (empty) = index, follow', max_length=17, verbose_name='robots'),
        ),
    ]
