# Generated by Django 2.2.4 on 2020-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20201104_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(max_length=1000, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
