# Generated by Django 2.2.4 on 2020-11-04 11:13

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_auto_20201104_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description', 'keywords', 'path'), required_languages=(), virtual_fields=True),
        ),
    ]
