# Generated by Django 2.2.4 on 2020-11-05 12:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_seo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Min resolution: 200 x 200 px. Suggested resolution: 1200 x 630 px (1.9:1). <a href="https://developers.facebook.com/docs/sharing/webmasters/images/" target="_blank">Read more</a>.', max_length=8192, upload_to='images', verbose_name='image'),
        ),
    ]
