# Generated by Django 2.2.4 on 2020-09-03 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='in period', null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(blank=True, choices=[('DAY', 'day'), ('MONTH', 'month'), ('YEAR', 'year')], default='DAY', max_length=5, verbose_name='period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, help_text='EUR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
