# Generated by Django 2.2.4 on 2020-06-18 19:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('i18n', modeltrans.fields.TranslationField(fields=('question', 'answer'), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'frequently asked question',
                'verbose_name_plural': 'frequently asked questions',
                'ordering': ('question',),
            },
        ),
        migrations.AddIndex(
            model_name='faq',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='faqs_faq_i18n_466a4f_gin'),
        ),
    ]
