# Generated by Django 2.2.4 on 2020-06-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
                ('distance', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='distance')),
            ],
            options={
                'verbose_name': 'race',
                'verbose_name_plural': 'races',
                'ordering': ('title',),
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
            ],
            options={
                'verbose_name': 'training',
                'verbose_name_plural': 'trainings',
                'ordering': ('title',),
            },
            bases=('listings.listing',),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='distance'),
        ),
    ]
