# Generated by Django 2.2.4 on 2020-03-08 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('title',), 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='star_rating',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star rating'),
        ),
    ]
