# Generated by Django 2.2.4 on 2020-06-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200603_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=None, help_text='min', null=True, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ('title',),
            },
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='km', null=True, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='km', null=True, verbose_name='distance'),
        ),
    ]
