# Generated by Django 2.2.4 on 2020-03-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200308_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='type',
        ),
    ]
