# Generated by Django 2.2.4 on 2020-06-08 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200608_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='difficulty'),
        ),
    ]
