# Generated by Django 2.2.4 on 2020-03-11 17:54

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200309_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('title',),
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ('title',),
            },
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='photo or image', max_length=1024, upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('ENTRY', 'entry'), ('HOUR', 'hour'), ('DAY', 'day'), ('NIGHT', 'night')], max_length=5, verbose_name='price unit'),
        ),
    ]
