# Generated by Django 2.2.4 on 2020-03-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200308_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ('title',), 'verbose_name': 'vacation', 'verbose_name_plural': 'vacations'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='street',
        ),
    ]
