# Generated by Django 2.2.4 on 2020-03-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200308_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(blank=True, help_text='street, postcode, city', max_length=500, verbose_name='address'),
        ),
    ]
