# Generated by Django 2.2.4 on 2020-06-11 10:56

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_awaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='medal',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='photo or image', max_length=1024, upload_to='images', verbose_name='medal'),
        ),
    ]
