# Generated by Django 2.2.4 on 2020-06-18 08:06

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_race_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
