# Generated by Django 2.2.4 on 2020-06-18 08:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_i18n'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='listings_ge_i18n_292915_gin'),
        ),
    ]
