# Generated by Django 2.2.4 on 2020-06-18 08:47

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200618_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'slug', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
