# Generated by Django 2.2.4 on 2020-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200308_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('PERSON', 'person'), ('DAY', 'day'), ('NIGHT', 'night'), ('PERSON_NIGHT', 'person per night')], max_length=12, verbose_name='price per unit'),
        ),
    ]
