# Generated by Django 2.2.4 on 2020-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200308_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatanddrink',
            name='booking_period',
            field=models.CharField(blank=True, choices=[('HOUR', 'hour'), ('DAY', 'day'), ('NIGHT', 'night')], max_length=5, verbose_name='booking period'),
        ),
        migrations.AddField(
            model_name='eatanddrink',
            name='bookings_enabled',
            field=models.BooleanField(default=True, verbose_name='bookings enabled'),
        ),
        migrations.AddField(
            model_name='eatanddrink',
            name='bookings_max_period',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='max period'),
        ),
        migrations.AddField(
            model_name='eatanddrink',
            name='bookings_min_period',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='min period'),
        ),
        migrations.AddField(
            model_name='eatanddrink',
            name='bookings_min_persons',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='min persons'),
        ),
        migrations.AddField(
            model_name='eatanddrink',
            name='capacity',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='capacity'),
        ),
    ]
