# Generated by Django 2.2.4 on 2020-03-08 14:40

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200308_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, db_index=True, default=None, null=True, verbose_name='datetime range'),
        ),
    ]
