# Generated by Django 2.2.4 on 2020-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_purchaseditem_option'),
        ('listings', '0012_auto_20200623_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='options',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='commerce.Option', verbose_name='options'),
        ),
    ]
