# Generated by Django 2.2.4 on 2020-03-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_event_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date',
        ),
    ]
