# Generated by Django 2.2.4 on 2020-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200308_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_per_person',
            field=models.BooleanField(default=False, verbose_name='price per person'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('ENTRY', 'entry'), ('HOUR', 'hour'), ('DAY', 'day'), ('NIGHT', 'night')], max_length=5, verbose_name='price per unit'),
        ),
    ]
