# Generated by Django 2.2.4 on 2020-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20200706_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.CharField(choices=[('STOCK', 'stock'), ('INFINITE', 'infinite')], default='STOCK', max_length=8, verbose_name='availability'),
        ),
    ]
