# Generated by Django 2.2.4 on 2020-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.CharField(choices=[('STOCK', 'stock'), ('INFINITE', 'infinite'), ('DIGITAL_GOODS', 'digital goods')], default='STOCK', max_length=13, verbose_name='availability'),
        ),
    ]
