# Generated by Django 2.2.9 on 2021-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20210320_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='video_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='video URL'),
        ),
    ]
