# Generated by Django 2.2.14 on 2023-11-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20231112_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='ordering', verbose_name='weight')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Group')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
            ],
            options={
                'verbose_name': 'Group listing',
                'verbose_name_plural': 'Group listings',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='groups', through='listings.GroupListing', to='listings.Listing', verbose_name='listings'),
        ),
    ]
