# Generated by Django 2.2.14 on 2023-11-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20231112_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouplisting',
            options={'ordering': ('weight',), 'verbose_name': 'Group listing', 'verbose_name_plural': 'Group listings'},
        ),
    ]
