# Generated by Django 2.2.4 on 2020-03-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lexicons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationamenity',
            options={'ordering': ('title',), 'verbose_name': 'accommodation amenity', 'verbose_name_plural': 'accommodation amenities'},
        ),
        migrations.AlterModelOptions(
            name='accommodationtype',
            options={'ordering': ('title',), 'verbose_name': 'accommodation type', 'verbose_name_plural': 'accommodation types'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ('title',), 'verbose_name': 'property type', 'verbose_name_plural': 'property types'},
        ),
        migrations.AlterField(
            model_name='category',
            name='listing_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='listing type'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'listing_type')},
        ),
    ]
