# Generated by Django 2.2.4 on 2020-06-03 12:57

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True),
        ),
    ]
