# Generated by Django 2.2.4 on 2020-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=5120, null=True, upload_to='locations', verbose_name='photo'),
        ),
    ]
