# Generated by Django 2.2.4 on 2020-06-03 13:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0002_category_i18n'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='lexicons_ca_i18n_5dae3a_gin'),
        ),
    ]
