# Generated by Django 2.2.4 on 2020-03-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_accommodation_type'),
        ('lexicons', '0003_auto_20200308_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationType',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
