# Generated by Django 2.2.4 on 2020-06-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0004_auto_20200606_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='icon'),
        ),
    ]
