# Generated by Django 2.2.4 on 2020-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0005_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
