# Generated by Django 2.2.4 on 2020-06-18 08:06

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0006_auto_20200608_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'slug', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
