# Generated by Django 2.2.9 on 2021-02-12 09:47

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0007_auto_20200618_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'slug'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('description',), required_languages=(), virtual_fields=True),
        ),
    ]
