# Generated by Django 2.2.9 on 2021-02-12 09:50

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0008_auto_20210212_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationamenity',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'slug', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
