# Generated by Django 2.2.4 on 2020-06-09 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='EUR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
