# Generated by Django 2.2.4 on 2020-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_from',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='book from'),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_to',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='book to'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hash_key',
            field=models.CharField(db_index=True, default=None, max_length=40, unique=True, verbose_name='hash key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_persons',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='number of persons'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('AWAITING_APPROVAL', 'Awaiting approval'), ('PENDING_PAYMENT', 'Pending payment'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show'), ('COMPLETED', 'Completed')], default='AWAITING_APPROVAL', max_length=17, verbose_name='status'),
        ),
    ]
