# Generated by Django 2.2.4 on 2020-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, help_text='URL', verbose_name='website'),
        ),
    ]
