# Generated by Django 2.2.4 on 2020-10-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-is_main', 'title'), 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main partner'),
        ),
    ]
